language: php

php:
  - 7.2

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

before_install:
  - mysql -e 'CREATE DATABASE travis;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('secret') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -psecret
  - sudo service mysql restart

script:
  - vendor/bin/phpunit

services:
  - mysql

cache:
  directories:
    - vendor